name: mlsecops
dependencies:
  - python=3.9
  - pip
  - pip:
    - fastapi
    - uvicorn
    - pandas
    - torch
    - mlflow
    - streamlit
    - evidently
    - apache-airflow
    - python-dotenv
    - requests
