name: mlsecops
dependencies:
  - python=3.9
  - pip
  - pip:
    - fastapi
    - uvicorn
    - pandas
    - scikit-learn
    - meteostat
    - geopy
    - matplotlib
    - seaborn
    - mlflow
    - streamlit
    - evidently
    - apache-airflow
    - python-dotenv
    - requests
    - email-validator
